version: '3.8'

services:
  web:
    build:
      context: ./WildlifeTracker
    ports:
      - "8000:80"
      - "8001:443"
    depends_on:
      - sqlserver
    environment:
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/https-dev.pfx
      - ASPNETCORE_Kestrel__Certificates__Default__Password=Test123!
      - ASPNETCORE_URLS=https://+;http://+
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=WildlifeTracker;User Id=sa;Password=Test123!;TrustServerCertificate=True;
    volumes:
      - ./WildlifeTracker/https-dev.pfx:/https/https-dev.pfx:ro
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      SA_PASSWORD: "Test123!"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - sql_data:/var/opt/mssql

volumes:
  sql_data:
