services:
  wildlifetracker:
    image: ${DOCKER_REGISTRY-}wildlifetracker
    build:
      context: .
      dockerfile: WildlifeTracker/Dockerfile
    depends_on:
      - sqlserver
    environment:
      - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=WildlifeTracker;User Id=sa;Password=Test123!;TrustServerCertificate=True;
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      SA_PASSWORD: "Test123!"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - sql_data:/var/opt/mssql

volumes:
  sql_data:
